# Generated by Django 3.1.12 on 2025-02-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.URLField(blank=True, null=True)),
                ('service', models.CharField(default='mobile', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screen_size', models.CharField(blank=True, max_length=20, null=True)),
                ('ram', models.CharField(blank=True, max_length=10, null=True)),
                ('storage', models.CharField(blank=True, max_length=10, null=True)),
                ('camera', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Mobile Device',
                'verbose_name_plural': 'Mobile Devices',
            },
        ),
    ]
